Update readme
emelysalmeron/to-do-list-group5 pull request #38
Opened 2021-08-23 07:18 UTC by Moamin-AbuEwaida

I updated the readme file to have the project's info

2021-08-23 07:45 UTC, Moamin-AbuEwaida commented
This PR includes Hasan's CSS files :thinking:

2021-08-23 10:40 UTC, rayanejsilva requested changes
@Moamin-AbuEwaida Good job. I just added two small suggestions. :)

2021-08-23 10:40 UTC, rayanejsilva commented on README.md
> +A todo list , the objective is build the app using Javascript to create DOM elements during the user interaction with the app interface .
This group project is part of [HackYourFuture Belgium](https://hackyourfuture.be/) module **Separation of concerns**. Our objective is to build an app using Javascript to create DOM elements during the user interaction with the app interface .

2021-08-23 10:40 UTC, rayanejsilva commented on README.md
> +- VSC code
VSCode

2021-08-24 18:56 UTC, emelysalmeron approved these changes

2021-08-26 07:40 UTC, Moamin-AbuEwaida commented on README.md
> +- VSC code
Oh yeah, would be great to add VS code :+1:

2021-08-26 08:01 UTC, rayanejsilva commented on README.md
> +- VSC code
@Moamin-AbuEwaida you already added it before. My comment was about the spelling mistake. **VSC code** --> _VSCode_

2021-08-26 15:23 UTC, rayanejsilva approved these changes

2021-08-26 15:23 UTC, merged